services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite+aiosqlite:////app/data/test.db
    volumes:
      - ./backend:/app
      - ./frontend/build:/app/static
      - ./backend/data:/app/data
    working_dir: /app
    user: root
    command: >
      sh -c "mkdir -p /app/data &&
             touch /app/data/test.db &&
             chown nobody:nogroup /app/data/test.db &&
             chmod 666 /app/data/test.db &&
             mkdir -p /app/static/_app &&
             python scripts/populate_test_data.py &&
             uvicorn app:app --host 0.0.0.0 --port 8000"

volumes:
  frontend_static: